# Expenses Constants

EXPENSE_RENT = 'Rent'
EXPENSE_UTILITIES = 'Utilities'
EXPENSE_SALARIES = 'Salaries'
EXPENSE_SUPPLIER_PAYMENT = 'Supplier Payment'
EXPENSE_MARKETING = 'Marketing'
EXPENSE_OTHERS = 'Others'

EXPENSE_CATEGORIES = [
    EXPENSE_RENT,
    EXPENSE_UTILITIES,
    EXPENSE_SALARIES,
    EXPENSE_SUPPLIER_PAYMENT,
    EXPENSE_MARKETING,
    EXPENSE_OTHERS
]

EXPENSE_DRAFT = 'Draft'
EXPENSE_APPROVED = 'Approved'
EXPENSE_PAID = 'Paid'

EXPENSE_STATUSES = [
    EXPENSE_DRAFT,
    EXPENSE_APPROVED,
    EXPENSE_PAID
]

PAYMENT_CASH = 'Cash'
PAYMENT_BANK_TRANSFER = 'Bank Transfer'
PAYMENT_UPI = 'UPI'
PAYMENT_CHECK = 'Check'

PAYMENT_MODES = [
    PAYMENT_CASH,
    PAYMENT_BANK_TRANSFER,
    PAYMENT_UPI,
    PAYMENT_CHECK
]
