# HRMS Constants

# Attendance Statuses
ATTENDANCE_PRESENT = 'Present'
ATTENDANCE_ABSENT = 'Absent'
ATTENDANCE_HALF_DAY = 'Half-Day'
ATTENDANCE_LATE = 'Late'
ATTENDANCE_ON_LEAVE = 'On-Leave'

ATTENDANCE_STATUSES = [
    ATTENDANCE_PRESENT,
    ATTENDANCE_ABSENT,
    ATTENDANCE_HALF_DAY,
    ATTENDANCE_LATE,
    ATTENDANCE_ON_LEAVE
]

# Salary Slip Statuses
PAYROLL_DRAFT = 'Draft'
PAYROLL_APPROVED = 'Approved'
PAYROLL_PAID = 'Paid'
PAYROLL_CANCELLED = 'Cancelled'

PAYROLL_STATUSES = [
    PAYROLL_DRAFT,
    PAYROLL_APPROVED,
    PAYROLL_PAID,
    PAYROLL_CANCELLED
]

# Payment Modes
PAYMENT_CASH = 'Cash'
PAYMENT_BANK_TRANSFER = 'Bank Transfer'
PAYMENT_UPI = 'UPI'
PAYMENT_CHECK = 'Check'

PAYMENT_MODES = [
    PAYMENT_CASH,
    PAYMENT_BANK_TRANSFER,
    PAYMENT_UPI,
    PAYMENT_CHECK
]
