# Billing & POS Constants

# Default GST Rates in India
GST_RATE_EXEMPT = 0.0
GST_RATE_5 = 5.0
GST_RATE_12 = 12.0
GST_RATE_18 = 18.0
GST_RATE_28 = 28.0

GST_RATES = [
    GST_RATE_EXEMPT,
    GST_RATE_5,
    GST_RATE_12,
    GST_RATE_18,
    GST_RATE_28
]

# Payment Modes
PAYMENT_MODE_CASH = 'Cash'
PAYMENT_MODE_CARD = 'Card'
PAYMENT_MODE_UPI = 'UPI'
PAYMENT_MODE_NETBANKING = 'NetBanking'

PAYMENT_MODES = [
    PAYMENT_MODE_CASH,
    PAYMENT_MODE_CARD,
    PAYMENT_MODE_UPI,
    PAYMENT_MODE_NETBANKING
]

# Invoice Statuses
STATUS_PAID = 'Paid'
STATUS_UNPAID = 'Unpaid'
STATUS_PARTIAL = 'Partial'

INVOICE_STATUSES = [
    STATUS_PAID,
    STATUS_UNPAID,
    STATUS_PARTIAL
]
